prettier autofix

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -1,4 +1,5 @@
 name: "PROD DEPLOYMENT"
+
 on:
   push:
     branches:
@@ -9,7 +10,17 @@ permissions:
   contents: read
 
 jobs:
+  check_branch:
+    runs-on: ubuntu-latest
+    steps:
+      - name: Check branch
+        if: github.base_ref == 'main' && github.head_ref != 'stage'
+        run: |
+          echo "ERROR: You can only merge to main from Stage."
+          exit 1
+
   terraform:
+    needs: validate-branch
     uses: ./.github/workflows/terraform.yml
     with:
       environment: "prod"
